name: Build and Push Odoo image

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on
env: 
  DOCKER_REGISTRY: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{vars.VERSION_PRODUCTION}}
# Define jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        
      - name: Build Docker image
        run: docker build -t $DOCKER_REGISTRY .

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_REGISTRY

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
     - name: Install sshpass
       run: 'if ! command -v sshpass &> /dev/null; then sudo apt-get install -y sshpass; fi'
     - name: Pull and run Docker image
       run: |
          sshpass -p ${{secrets.SSH_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} "
          
          docker stop ${{vars.ODOO_CONTAINER_NAME_PRODUCTION}} || true
          docker rm ${{vars.ODOO_CONTAINER_NAME_PRODUCTION}} || true
          docker rmi $DOCKER_REGISTRY || true
          
          docker pull $DOCKER_REGISTRY
          docker run -d -p ${{vars.ODOO_LISTEN_PORT_PRODUCTION}}:${{vars.ODOO_PORT}} --name ${{vars.ODOO_CONTAINER_NAME_PRODUCTION}} -v ${{vars.ODOO_FILESTORE_VOLUME_PRODUCTION}}:${{vars.ODOO_FILESTORE_PATH}} $DOCKER_REGISTRY
          docker cp ${{vars.ODOO_CONFIG_FILE}} ${{vars.ODOO_CONTAINER_NAME_PRODUCTION}}:${{vars.ODOO_ROOT_CONFIG_FILE}}
          docker restart ${{vars.ODOO_CONTAINER_NAME_PRODUCTION}}
          "
