name: Build and Push Odoo image

# Controls when the workflow will run
on:
  push:
    branches:
      - dev  # or the branch you want to trigger the workflow on

# Define jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{vars.VERSION_DEV}} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{vars.VERSION_DEV}}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
     - name: Install sshpass
       run: 'if ! command -v sshpass &> /dev/null; then sudo apt-get install -y sshpass; fi'
     - name: Pull and run Docker image
       run: |
          sshpass -p ${{secrets.SSH_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} "
          
          docker stop ${{vars.ODOO_CONTAINER_NAME_DEV}} || true
          docker rm ${{vars.ODOO_CONTAINER_NAME_DEV}} || true
          docker rmi ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{vars.VERSION_DEV}} || true
          
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{vars.VERSION_DEV}}
          docker run -d -p ${{vars.ODOO_LISTEN_PORT_DEV}}:${{vars.ODOO_PORT}} --name ${{vars.ODOO_CONTAINER_NAME_DEV}} -v ${{vars.ODOO_FILESTORE_VOLUME_DEV}}:${{vars.ODOO_FILESTORE_PATH}} ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{vars.VERSION_DEV}}
          "